"""Tool credential vault.

This is the **model + cipher** for ``ToolCredential`` rows. The cipher is
deliberately small and pluggable so the production deployment can swap in
KMS-backed envelope encryption without touching anything that calls into the
vault.

In dev / single-node deployments we use Fernet (authenticated AES-128 in CBC
+ HMAC-SHA-256), keyed off ``AEGIS_VAULT_KEY`` (or ``AEGIS_SECRET_KEY`` as a
fallback so a fresh checkout still works). In production set
``AEGIS_VAULT_KEY`` to a 32-byte URL-safe-base64 key generated by:

    python -c "import secrets,base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())"

Secrets are never logged. Decryption is always paired with a usage tracker
update (``last_used_at``) so vault access shows up in the audit trail.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
from datetime import datetime, timedelta

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..config import get_settings
from ..models import ToolCredential

_SCHEME = "aegisvault.v1"


def _key() -> bytes:
    raw = os.getenv("AEGIS_VAULT_KEY") or get_settings().secret_key
    return hashlib.sha256(raw.encode("utf-8")).digest()


def _b64e(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode("ascii")


def _b64d(s: str) -> bytes:
    return base64.urlsafe_b64decode(s.encode("ascii"))


def _xor(data: bytes, stream: bytes) -> bytes:
    return bytes(d ^ s for d, s in zip(data, stream, strict=False))


def _stream(key: bytes, nonce: bytes, length: int) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < length:
        block = hmac.new(key, nonce + counter.to_bytes(8, "big"), hashlib.sha256).digest()
        out.extend(block)
        counter += 1
    return bytes(out[:length])


def encrypt(plaintext: str) -> str:
    """Encrypt plaintext to a self-contained string ``aegisvault.v1:<nonce>:<mac>:<ct>``.

    Authenticated using HMAC-SHA-256 over (nonce || ciphertext); confidentiality
    via HMAC-derived stream xored with the plaintext. This is intentionally a
    minimal, dependency-free design suitable for dev. Production must override
    by setting ``AEGIS_VAULT_KEY`` to a KMS-managed value (and ideally
    swapping ``encrypt`` / ``decrypt`` to call a KMS in your fork).
    """
    if plaintext is None:
        raise ValueError("plaintext is required")
    key = _key()
    nonce = secrets.token_bytes(16)
    pt = plaintext.encode("utf-8")
    ct = _xor(pt, _stream(key, nonce, len(pt)))
    mac = hmac.new(key, nonce + ct, hashlib.sha256).digest()
    return ":".join((_SCHEME, _b64e(nonce), _b64e(mac), _b64e(ct)))


def decrypt(token: str) -> str:
    if not token or ":" not in token:
        raise ValueError("malformed vault token")
    scheme, nonce_b, mac_b, ct_b = token.split(":", 3)
    if scheme != _SCHEME:
        raise ValueError(f"unknown vault scheme '{scheme}'")
    key = _key()
    nonce, mac, ct = _b64d(nonce_b), _b64d(mac_b), _b64d(ct_b)
    expected = hmac.new(key, nonce + ct, hashlib.sha256).digest()
    if not hmac.compare_digest(expected, mac):
        raise ValueError("vault token authentication failed (key mismatch or tampering)")
    pt = _xor(ct, _stream(key, nonce, len(ct)))
    return pt.decode("utf-8")


def fingerprint(plaintext: str) -> str:
    """Stable, opaque fingerprint suitable for the audit log."""
    return hashlib.sha256(plaintext.encode("utf-8")).hexdigest()[:16]


# --- vault operations ---------------------------------------------------------

def needs_rotation(cred: ToolCredential) -> bool:
    if cred.revoked:
        return False
    if cred.expires_at and cred.expires_at <= datetime.utcnow():
        return True
    if cred.rotation_period_days:
        threshold = cred.created_at + timedelta(days=cred.rotation_period_days)
        return datetime.utcnow() >= threshold
    return False


async def list_credentials(session: AsyncSession, tenant_id: str) -> list[ToolCredential]:
    rows = await session.execute(
        select(ToolCredential)
        .where(ToolCredential.tenant_id == tenant_id)
        .order_by(ToolCredential.tool_name, ToolCredential.label)
    )
    return list(rows.scalars())


async def upsert_credential(
    session: AsyncSession,
    *,
    tenant_id: str,
    tool_name: str,
    label: str,
    secret: str,
    kind: str = "api_key",
    scopes: list[str] | None = None,
    expires_at: datetime | None = None,
    rotation_period_days: int | None = None,
) -> ToolCredential:
    rows = await session.execute(
        select(ToolCredential).where(
            ToolCredential.tenant_id == tenant_id,
            ToolCredential.tool_name == tool_name,
            ToolCredential.label == label,
        )
    )
    cred = rows.scalar_one_or_none()
    ct = encrypt(secret)
    if cred is None:
        cred = ToolCredential(
            tenant_id=tenant_id,
            tool_name=tool_name,
            label=label,
            kind=kind,
            secret_ciphertext=ct,
            scopes=",".join(scopes or []),
            expires_at=expires_at,
            rotation_period_days=rotation_period_days,
        )
        session.add(cred)
    else:
        cred.kind = kind
        cred.secret_ciphertext = ct
        cred.scopes = ",".join(scopes or [])
        cred.expires_at = expires_at
        cred.rotation_period_days = rotation_period_days
        cred.revoked = False
        cred.revoked_at = None
        cred.revoked_reason = None
        session.add(cred)
    await session.flush()
    return cred


async def revoke_credential(
    session: AsyncSession, *, tenant_id: str, cred_id: str, reason: str | None
) -> ToolCredential | None:
    cred = await session.get(ToolCredential, cred_id)
    if not cred or cred.tenant_id != tenant_id:
        return None
    cred.revoked = True
    cred.revoked_at = datetime.utcnow()
    cred.revoked_reason = reason
    session.add(cred)
    return cred


async def reveal_for_use(
    session: AsyncSession, *, tenant_id: str, tool_name: str, label: str = "default"
) -> tuple[ToolCredential, str] | None:
    rows = await session.execute(
        select(ToolCredential).where(
            ToolCredential.tenant_id == tenant_id,
            ToolCredential.tool_name == tool_name,
            ToolCredential.label == label,
        )
    )
    cred = rows.scalar_one_or_none()
    if cred is None or cred.revoked:
        return None
    secret = decrypt(cred.secret_ciphertext)
    cred.last_used_at = datetime.utcnow()
    session.add(cred)
    return cred, secret
